org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


## Mod Properties
modId=examplemod
modName=Example Mod
modLicense=MIT
modVersion=1.0.0
modGroupId=com.dousiyo.examplemod
modAuthors=dousiyo
modDescription=
modDisplayUrl=
modIssueTrackerUrl=
modCredits=


## Fabric Mod Properties
modFabricEntrypoint=com.dousiyo.examplemod.ModMain
modFabricClientEntrypoint=com.dousiyo.examplemod.client.ModClient
