org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


## Mod Properties
modId=onlyzombiesspawn
modName=Only Zombies Spawn
modLicense=MIT
modVersion=1.0.1
modGroupId=com.dousiyo
modAuthors=dousiyo
modDescription=Restricts hostile mob spawns to regular zombies.
modDisplayUrl=
modIssueTrackerUrl=
modCredits=


## Fabric Mod Properties
modFabricEntrypoint=com.dousiyo.onlyzombiesspawn.OnlyZombiesSpawn
modFabricClientEntrypoint=com.dousiyo.onlyzombiesspawn.client.ModClient
